# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|
  config.vm.box = "ubuntu/trusty64"

  config.vm.define "cnc" do |cnc|
    cnc.vm.provision "file", source: "cnc.sh", destination: "/tmp/cnc"
    cnc.vm.provision :shell, path: "provision.sh"
    cnc.vm.synced_folder "~/vagrant", "/vagrant"
    cnc.vm.synced_folder "~/vagrant/myproject", "/home/vagrant/myproject"

    cnc.vm.provider "virtualbox" do |v|
      v.name = "cnc"
      v.memory = 2048
      v.cpus = 8
    end
  end
end
